// ==========================================================================
// EDOPro Script Studio — données de référence (constantes du moteur)
// Chargé AVANT app.js. Expose window.YGO_DATA.
// NB: les hex/id des archétypes et cartes de référence sont indicatifs —
// vérifiez toujours contre votre expansions/archetype_setcode_constants.lua
// et votre .cdb avant de livrer un script en production.
// ==========================================================================

window.YGO_DATA = {
  constants: {
    EVENT: [
      { const: "EVENT_FREE_CHAIN", label: "Chaîne libre (jeu rapide)" },
      { const: "EVENT_SUMMON_SUCCESS", label: "Invocation normale réussie" },
      { const: "EVENT_SPSUMMON_SUCCESS", label: "Invocation spéciale réussie" },
      { const: "EVENT_FLIP_SUMMON_SUCCESS", label: "Invocation retournée réussie" },
      { const: "EVENT_FLIP", label: "Carte retournée face recto" },
      { const: "EVENT_ATTACK_ANNOUNCE", label: "Déclaration d'attaque" },
      { const: "EVENT_ATTACK", label: "Attaque déclarée (résolue)" },
      { const: "EVENT_BATTLE_START", label: "Début de la bataille" },
      { const: "EVENT_BATTLED", label: "Combat résolu" },
      { const: "EVENT_BATTLE_DESTROYED", label: "Détruite au combat" },
      { const: "EVENT_DESTROYED", label: "Carte détruite" },
      { const: "EVENT_REMOVE", label: "Carte bannie" },
      { const: "EVENT_TO_GRAVE", label: "Envoyée au cimetière" },
      { const: "EVENT_TO_HAND", label: "Envoyée en main" },
      { const: "EVENT_TO_DECK", label: "Envoyée au deck" },
      { const: "EVENT_DISCARD", label: "Carte défaussée" },
      { const: "EVENT_DISCARD_HAND", label: "Défausse depuis la main" },
      { const: "EVENT_DRAW", label: "Carte piochée" },
      { const: "EVENT_DAMAGE", label: "Dégâts infligés" },
      { const: "EVENT_RECOVER", label: "Points de vie récupérés" },
      { const: "EVENT_EQUIP", label: "Carte équipée" },
      { const: "EVENT_CONTROL_CHANGED", label: "Contrôle changé" },
      { const: "EVENT_CHAINING", label: "Chaîne en cours de construction" },
      { const: "EVENT_CHAIN_SOLVING", label: "Résolution de chaîne en cours" },
      { const: "EVENT_CHAIN_SOLVED", label: "Chaîne résolue" },
      { const: "EVENT_CHAIN_NEGATED", label: "Chaîne annulée" },
      { const: "EVENT_CHAIN_END", label: "Fin de la chaîne" },
      { const: "EVENT_PHASE_START", label: "Début de phase (générique)" },
      { const: "EVENT_DRAW_PHASE", label: "Début de la Draw Phase" },
      { const: "EVENT_STANDBY_PHASE", label: "Début de la Standby Phase" },
      { const: "EVENT_MAIN_PHASE", label: "Début de la Main Phase" },
      { const: "EVENT_BATTLE_PHASE", label: "Début de la Battle Phase" },
      { const: "EVENT_BATTLE_PHASE_END", label: "Fin de la Battle Phase" },
      { const: "EVENT_MAIN_PHASE_END", label: "Fin de la Main Phase" },
      { const: "EVENT_END_PHASE", label: "Début de l'End Phase" },
      { const: "EVENT_ADJUST", label: "Ajustement (post-résolution)" },
    ],
    LOCATION: [
      { const: "LOCATION_DECK", label: "Deck principal" },
      { const: "LOCATION_HAND", label: "Main" },
      { const: "LOCATION_MZONE", label: "Zone Monstre" },
      { const: "LOCATION_SZONE", label: "Zone Magie/Piège" },
      { const: "LOCATION_GRAVE", label: "Cimetière" },
      { const: "LOCATION_REMOVED", label: "Zone bannie" },
      { const: "LOCATION_EXTRA", label: "Extra Deck" },
      { const: "LOCATION_OVERLAY", label: "Matériel Xyz" },
      { const: "LOCATION_ONFIELD", label: "Sur le terrain (MZone + SZone)" },
      { const: "LOCATION_FZONE", label: "Zone de Terrain (Field Zone)" },
      { const: "LOCATION_PZONE", label: "Zone Pendule" },
      { const: "LOCATION_DECKBOT", label: "Fond du Deck" },
      { const: "LOCATION_DECKSHF", label: "Deck (après mélange)" },
    ],
    EFFECT_TYPE: [
      { const: "EFFECT_TYPE_SINGLE", label: "Simple (nécessite un code + range)" },
      { const: "EFFECT_TYPE_FIELD", label: "Continu de terrain (statique)" },
      { const: "EFFECT_TYPE_EQUIP", label: "Effet d'équipement" },
      { const: "EFFECT_TYPE_ACTIVATE", label: "Activation (Magie/Piège)" },
      { const: "EFFECT_TYPE_TRIGGER_O", label: "Trigger optionnel" },
      { const: "EFFECT_TYPE_TRIGGER_F", label: "Trigger obligatoire (forced)" },
      { const: "EFFECT_TYPE_QUICK_O", label: "Jeu rapide optionnel" },
      { const: "EFFECT_TYPE_QUICK_F", label: "Jeu rapide obligatoire" },
      { const: "EFFECT_TYPE_IGNITION", label: "Ignition (activable en Main Phase)" },
      { const: "EFFECT_TYPE_CONTINUOUS", label: "Continu (persistant)" },
      { const: "EFFECT_TYPE_FLIP", label: "Effet Flip" },
      { const: "EFFECT_TYPE_ACTIONS", label: "Modificateur d'action (interne)" },
      { const: "EFFECT_TYPE_XMATERIAL", label: "Lié au matériel Xyz" },
      { const: "EFFECT_TYPE_RULE", label: "Effet de règle (non copiable)" },
    ],
    CATEGORY: [
      { const: "CATEGORY_DESTROY", label: "Destruction" },
      { const: "CATEGORY_REMOVE", label: "Bannissement" },
      { const: "CATEGORY_TOHAND", label: "Retour/ajout en main" },
      { const: "CATEGORY_TODECK", label: "Retour au deck" },
      { const: "CATEGORY_TOGRAVE", label: "Envoi au cimetière" },
      { const: "CATEGORY_SPECIAL_SUMMON", label: "Invocation spéciale" },
      { const: "CATEGORY_DAMAGE", label: "Dégâts" },
      { const: "CATEGORY_RECOVER", label: "Récupération de LP" },
      { const: "CATEGORY_EQUIP", label: "Équipement" },
      { const: "CATEGORY_ATKCHANGE", label: "Changement d'ATK" },
      { const: "CATEGORY_DEFCHANGE", label: "Changement de DEF" },
      { const: "CATEGORY_DRAW", label: "Pioche" },
      { const: "CATEGORY_DISCARD", label: "Défausse" },
      { const: "CATEGORY_COUNTER", label: "Contre (négation par contre-carte)" },
      { const: "CATEGORY_SEARCH", label: "Recherche dans le deck" },
      { const: "CATEGORY_NEGATE", label: "Négation" },
      { const: "CATEGORY_DECKDES", label: "Destruction du deck (mill)" },
      { const: "CATEGORY_DISABLE", label: "Désactivation d'effet" },
      { const: "CATEGORY_POSITION", label: "Changement de position" },
      { const: "CATEGORY_CONTROL", label: "Changement de contrôle" },
      { const: "CATEGORY_HANDES", label: "Défausse forcée (hand destruction)" },
      { const: "CATEGORY_FUSION", label: "Invocation Fusion" },
      { const: "CATEGORY_RITUAL", label: "Invocation Rituelle" },
      { const: "CATEGORY_COUNTER_ADD", label: "Ajout de compteurs" },
    ],
    EFFECT_FLAG: [
      { const: "EFFECT_FLAG_CARD_TARGET", label: "Effet à cible (déclare une cible)" },
      { const: "EFFECT_FLAG_DAMAGE_STEP", label: "Activable en Damage Step" },
      { const: "EFFECT_FLAG_IGNORE_IMMUNE", label: "Ignore l'immunité de la cible" },
      { const: "EFFECT_FLAG_ABSOLUTE_TARGET", label: "Cible absolue (non substituable)" },
      { const: "EFFECT_FLAG_FUNC_VALUE", label: "Valeur calculée par fonction" },
      { const: "EFFECT_FLAG_PLAYER_TARGET", label: "Cible un joueur" },
      { const: "EFFECT_FLAG_SINGLE_RANGE", label: "Portée simple uniquement" },
      { const: "EFFECT_FLAG_INITIAL", label: "Actif dès l'invocation" },
      { const: "EFFECT_FLAG_COPY_INHERIT", label: "Hérité en cas de copie" },
      { const: "EFFECT_FLAG_UNCOPYABLE", label: "Non copiable" },
      { const: "EFFECT_FLAG_SET_AVAILABLE", label: "Actif carte face cachée" },
      { const: "EFFECT_FLAG_OWNER_RELATE", label: "Lié au contrôleur d'origine" },
      { const: "EFFECT_FLAG_DELAY", label: "Résolution différée (trigger)" },
      { const: "EFFECT_FLAG_CANNOT_DISABLE", label: "Ne peut pas être désactivé" },
      { const: "EFFECT_FLAG_CLIENT_HINT", label: "Affiche un hint client" },
    ],
    TIMING: [
      { const: "TIMING_SUMMON", label: "À l'invocation normale" },
      { const: "TIMING_SPSUMMON", label: "À l'invocation spéciale" },
      { const: "TIMING_FLIPSUMMON", label: "À l'invocation retournée" },
      { const: "TIMING_MSET", label: "À la pose d'un monstre" },
      { const: "TIMING_SSET", label: "À la pose d'une Magie/Piège" },
      { const: "TIMING_ATTACK", label: "À la déclaration d'attaque" },
      { const: "TIMING_DAMAGE_STEP", label: "Pendant le Damage Step" },
      { const: "TIMING_END_PHASE", label: "En End Phase" },
      { const: "TIMING_DRAW_PHASE", label: "En Draw Phase" },
      { const: "TIMING_STANDBY_PHASE", label: "En Standby Phase" },
      { const: "TIMING_MAIN_END", label: "En fin de Main Phase" },
      { const: "TIMING_BATTLE_START", label: "Au début de la Battle Phase" },
      { const: "TIMING_BATTLE_END", label: "À la fin de la Battle Phase" },
      { const: "TIMING_DESTROY", label: "Quand détruite" },
      { const: "TIMING_REMOVE", label: "Quand bannie" },
      { const: "TIMING_TOGRAVE", label: "Quand envoyée au cimetière" },
      { const: "TIMING_TOHAND", label: "Quand renvoyée en main" },
      { const: "TIMING_TODECK", label: "Quand renvoyée au deck" },
      { const: "TIMING_DRAW", label: "Quand une carte est piochée" },
    ],
    EFFECT_COUNT_CODE: [
      { const: "EFFECT_COUNT_CODE_OATH", label: "Serment — annulation empêche la réactivation" },
      { const: "EFFECT_COUNT_CODE_DUEL", label: "Une seule fois par duel" },
      { const: "EFFECT_COUNT_CODE_SINGLE", label: "Comptage indépendant par exemplaire" },
      { const: "EFFECT_COUNT_CODE_CHAIN", label: "Comptage par chaîne" },
    ],
    HINTMSG: [
      { const: "HINTMSG_DESTROY", label: "Sélectionnez une carte à détruire" },
      { const: "HINTMSG_REMOVE", label: "Sélectionnez une carte à bannir" },
      { const: "HINTMSG_TOHAND", label: "Sélectionnez une carte à ajouter en main" },
      { const: "HINTMSG_TODECK", label: "Sélectionnez une carte à renvoyer au deck" },
      { const: "HINTMSG_TOGRAVE", label: "Sélectionnez une carte à envoyer au cimetière" },
      { const: "HINTMSG_RELEASE", label: "Sélectionnez une carte à tribute/release" },
      { const: "HINTMSG_DISCARD", label: "Sélectionnez une carte à défausser" },
      { const: "HINTMSG_EQUIP", label: "Sélectionnez une cible à équiper" },
      { const: "HINTMSG_ATTACK", label: "Sélectionnez une cible d'attaque" },
      { const: "HINTMSG_DAMAGE", label: "Message: dégâts infligés" },
      { const: "HINTMSG_RECOVER", label: "Message: récupération de LP" },
      { const: "HINTMSG_SPSUMMON", label: "Sélectionnez une carte à invoquer spécialement" },
      { const: "HINTMSG_CONTROL", label: "Sélectionnez une carte à prendre le contrôle de" },
      { const: "HINTMSG_SUMMON", label: "Sélectionnez une carte à invoquer" },
      { const: "HINTMSG_SELECT", label: "Sélectionnez une carte" },
      { const: "HINTMSG_FUSION", label: "Sélectionnez les matériels de fusion" },
      { const: "HINTMSG_SYNCHRO", label: "Sélectionnez les matériels Synchro" },
      { const: "HINTMSG_XYZ", label: "Sélectionnez les matériels Xyz" },
      { const: "HINTMSG_LINK", label: "Sélectionnez les matériels Link" },
      { const: "HINTMSG_RITUAL", label: "Sélectionnez les tributs rituels" },
      { const: "HINTMSG_NEGATE", label: "Sélectionnez une cible à négocier/annuler" },
    ],
    REASON: [
      { const: "REASON_EFFECT", label: "Résultat d'un effet de carte" },
      { const: "REASON_COST", label: "Coût d'activation" },
      { const: "REASON_BATTLE", label: "Résultat de combat" },
      { const: "REASON_MATERIAL", label: "Utilisée comme matériel" },
      { const: "REASON_DESTROY", label: "Marqueur de destruction" },
      { const: "REASON_DISCARD", label: "Marqueur de défausse" },
      { const: "REASON_RULE", label: "Effet de règle du jeu" },
      { const: "REASON_SPSUMMON", label: "Lié à une invocation spéciale" },
      { const: "REASON_RELEASE", label: "Tribute/release" },
      { const: "REASON_TEMPORARY", label: "Bannissement temporaire" },
      { const: "REASON_RETURN", label: "Retour (bounce)" },
      { const: "REASON_FUSION", label: "Invocation Fusion" },
      { const: "REASON_SYNCHRO", label: "Invocation Synchro" },
      { const: "REASON_XYZ", label: "Invocation Xyz" },
      { const: "REASON_LINK", label: "Invocation Link" },
      { const: "REASON_RITUAL", label: "Invocation Rituelle" },
    ],
    PHASE: [
      { const: "PHASE_DRAW", label: "Draw Phase" },
      { const: "PHASE_STANDBY", label: "Standby Phase" },
      { const: "PHASE_MAIN1", label: "Main Phase 1" },
      { const: "PHASE_BATTLE_START", label: "Début de Battle Phase" },
      { const: "PHASE_BATTLE_STEP", label: "Battle Step" },
      { const: "PHASE_DAMAGE", label: "Damage Step" },
      { const: "PHASE_DAMAGE_CAL", label: "Calcul des dégâts" },
      { const: "PHASE_BATTLE", label: "Battle Phase (générique)" },
      { const: "PHASE_MAIN2", label: "Main Phase 2" },
      { const: "PHASE_END", label: "End Phase" },
    ],
  },

  // Archétypes (listed_series). Hex indicatifs — à vérifier contre
  // archetype_setcode_constants.lua avant utilisation en production.
  archetypes: [
    { const: "SETCODE_BLUE_EYES", label: "Blue-Eyes", hex: "0x6" },
    { const: "SETCODE_DARK_MAGICIAN", label: "Dark Magician", hex: "0x5a" },
    { const: "SETCODE_ELEMENTAL_HERO", label: "Elemental HERO", hex: "0x18" },
    { const: "SETCODE_BLACKWING", label: "Blackwing", hex: "0x6f" },
    { const: "SETCODE_SYNCHRON", label: "Synchron", hex: "0x53" },
    { const: "SETCODE_MELFFY", label: "Melffy", hex: "0x9a" },
    { const: "SETCODE_SKY_STRIKER", label: "Sky Striker", hex: "0x134" },
    { const: "SETCODE_SALAMANGREAT", label: "Salamangreat", hex: "0x113" },
    { const: "SETCODE_DRAGON_LINK", label: "Dragon Link (générique dragon)", hex: "0x27" },
    { const: "SETCODE_INFERNOID", label: "Infernoid", hex: "0xa9" },
    { const: "SETCODE_SUBTERROR", label: "SubTerror", hex: "0xaf" },
    { const: "SETCODE_ORCUST", label: "Orcust", hex: "0x117" },
    { const: "SETCODE_TRAPTRIX", label: "Traptrix", hex: "0xb4" },
    { const: "SETCODE_MEKK_KNIGHT", label: "Mekk-Knight", hex: "0x141" },
    { const: "SETCODE_SPRIGHT", label: "Spright", hex: "0x16e" },
    { const: "SETCODE_TEARLAMENT", label: "Tearlaments", hex: "0x175" },
    { const: "SETCODE_KASHTIRA", label: "Kashtira", hex: "0x178" },
    { const: "SETCODE_FIRE_KING", label: "Fire King", hex: "0xa4" },
    { const: "SETCODE_PURRELY", label: "Purrely", hex: "0x184" },
    { const: "SETCODE_VOICEOFTHEFORESTINCARNATE", label: "Voiceless Voice", hex: "0x18e" },
  ],

  // Cartes de référence (listed_names). Passcodes indicatifs — remplacez
  // par les vrais passcodes de votre .cdb avant utilisation en production.
  cards: [
    { const: "CARD_ASH_BLOSSOM", label: "Ash Blossom & Joyous Spring", id: 14558127 },
    { const: "CARD_EFFECT_VEILER", label: "Effect Veiler", id: 97268402 },
    { const: "CARD_MAXX_C", label: "Maxx \"C\"", id: 23434538 },
    { const: "CARD_GHOST_OGRE", label: "Ghost Ogre & Snow Rabbit", id: 59438930 },
    { const: "CARD_NIBIRU", label: "Nibiru, the Primal Being", id: 27204311 },
    { const: "CARD_INFINITE_IMPERMANENCE", label: "Infinite Impermanence", id: 10045474 },
    { const: "CARD_CALLED_BY_THE_GRAVE", label: "Called by the Grave", id: 24224830 },
    { const: "CARD_DROLL_LOCK_BIRD", label: "Droll & Lock Bird", id: 94145021 },
    { const: "CARD_POT_OF_DESIRES", label: "Pot of Desires", id: 35261759 },
    { const: "CARD_POT_OF_PROSPERITY", label: "Pot of Prosperity", id: 84211599 },
    { const: "CARD_MONSTER_REBORN", label: "Monster Reborn", id: 83764718 },
    { const: "CARD_TWIN_TWISTERS", label: "Twin Twisters", id: 87843002 },
    { const: "CARD_LIGHTNING_STORM", label: "Lightning Storm", id: 40390458 },
    { const: "CARD_TRAP_TRICK", label: "Trap Trick", id: 66396182 },
    { const: "CARD_DIMENSION_SHIFTER", label: "Dimension Shifter", id: 99433858 },
  ],

  counters: [
    { label: "Compteur de Sorts", const: "COUNTER_SPELL", hex: "0x1" },
    { label: "Compteur de Rituel", const: "COUNTER_RITUAL", hex: "0x2" },
    { label: "Compteur Lumière", const: "COUNTER_LIGHT", hex: "0x4" },
    { label: "Compteur Ténèbres", const: "COUNTER_DARK", hex: "0x8" },
    { label: "Compteur Union", const: "COUNTER_UNION", hex: "0x10" },
    { label: "Compteur de Bravoure", const: "COUNTER_BRAVE", hex: "0x20" },
    { label: "Compteur Magique", const: "COUNTER_MAGIC", hex: "0x40" },
    { label: "Compteur d'Âme", const: "COUNTER_SOUL", hex: "0x80" },
    { label: "Compteur de Bombe", const: "COUNTER_BOMB", hex: "0x100" },
    { label: "Compteur de Glace", const: "COUNTER_ICE", hex: "0x200" },
    { label: "Compteur de Crâne (Skull)", const: "COUNTER_SKULL", hex: "0x400" },
    { label: "Compteur de Fleur (Wild)", const: "COUNTER_WILD", hex: "0x800" },
  ],
};
